"""
✨ `Booking_KeyOutput` returns the primary key fields of table type `Booking`.

It has the same format as `Booking_Key`, but is only used as mutation return value.
"""
scalar Booking_KeyOutput
"""
✨ `Employee_KeyOutput` returns the primary key fields of table type `Employee`.

It has the same format as `Employee_Key`, but is only used as mutation return value.
"""
scalar Employee_KeyOutput
"""
✨ `Guest_KeyOutput` returns the primary key fields of table type `Guest`.

It has the same format as `Guest_Key`, but is only used as mutation return value.
"""
scalar Guest_KeyOutput
"""
✨ `Hotel_KeyOutput` returns the primary key fields of table type `Hotel`.

It has the same format as `Hotel_Key`, but is only used as mutation return value.
"""
scalar Hotel_KeyOutput
"""
✨ `JobType_KeyOutput` returns the primary key fields of table type `JobType`.

It has the same format as `JobType_Key`, but is only used as mutation return value.
"""
scalar JobType_KeyOutput
"""
✨ `Payment_KeyOutput` returns the primary key fields of table type `Payment`.

It has the same format as `Payment_Key`, but is only used as mutation return value.
"""
scalar Payment_KeyOutput
"""
✨ `Room_KeyOutput` returns the primary key fields of table type `Room`.

It has the same format as `Room_Key`, but is only used as mutation return value.
"""
scalar Room_KeyOutput
"""
✨ `RoomType_KeyOutput` returns the primary key fields of table type `RoomType`.

It has the same format as `RoomType_Key`, but is only used as mutation return value.
"""
scalar RoomType_KeyOutput
"""
✨ Generated data input type for table 'Booking'. It includes all necessary fields for creating or upserting rows into table.
"""
input Booking_Data {
  """
  ✨ Generated from Field `Booking`.`bookingId` of type `Int!`
  """
  bookingId: Int
  """
  ✨ `_expr` server value variant of `bookingId` (✨ Generated from Field `Booking`.`bookingId` of type `Int!`)
  """
  bookingId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `bookingId` (✨ Generated from Field `Booking`.`bookingId` of type `Int!`)
  """
  bookingId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`guestId` of type `Int!`
  """
  guestId: Int
  """
  ✨ `_expr` server value variant of `guestId` (✨ Generated from Field `Booking`.`guestId` of type `Int!`)
  """
  guestId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `guestId` (✨ Generated from Field `Booking`.`guestId` of type `Int!`)
  """
  guestId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`roomId` of type `Int!`
  """
  roomId: Int
  """
  ✨ `_expr` server value variant of `roomId` (✨ Generated from Field `Booking`.`roomId` of type `Int!`)
  """
  roomId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `roomId` (✨ Generated from Field `Booking`.`roomId` of type `Int!`)
  """
  roomId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`guest` of type `Guest!`
  """
  guest: Guest_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`room` of type `Room!`
  """
  room: Room_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`bookingDate` of type `Date!`
  """
  bookingDate: Date
  """
  ✨ `_date` server value variant of `bookingDate` (✨ Generated from Field `Booking`.`bookingDate` of type `Date!`)
  """
  bookingDate_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `bookingDate` (✨ Generated from Field `Booking`.`bookingDate` of type `Date!`)
  """
  bookingDate_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `bookingDate` (✨ Generated from Field `Booking`.`bookingDate` of type `Date!`)
  """
  bookingDate_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`bookingStatus` of type `String!`
  """
  bookingStatus: String
  """
  ✨ `_expr` server value variant of `bookingStatus` (✨ Generated from Field `Booking`.`bookingStatus` of type `String!`)
  """
  bookingStatus_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`checkInDate` of type `Date!`
  """
  checkInDate: Date
  """
  ✨ `_date` server value variant of `checkInDate` (✨ Generated from Field `Booking`.`checkInDate` of type `Date!`)
  """
  checkInDate_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `checkInDate` (✨ Generated from Field `Booking`.`checkInDate` of type `Date!`)
  """
  checkInDate_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `checkInDate` (✨ Generated from Field `Booking`.`checkInDate` of type `Date!`)
  """
  checkInDate_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`checkOutDate` of type `Date!`
  """
  checkOutDate: Date
  """
  ✨ `_date` server value variant of `checkOutDate` (✨ Generated from Field `Booking`.`checkOutDate` of type `Date!`)
  """
  checkOutDate_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `checkOutDate` (✨ Generated from Field `Booking`.`checkOutDate` of type `Date!`)
  """
  checkOutDate_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `checkOutDate` (✨ Generated from Field `Booking`.`checkOutDate` of type `Date!`)
  """
  checkOutDate_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`numberOfGuests` of type `Int!`
  """
  numberOfGuests: Int
  """
  ✨ `_expr` server value variant of `numberOfGuests` (✨ Generated from Field `Booking`.`numberOfGuests` of type `Int!`)
  """
  numberOfGuests_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `numberOfGuests` (✨ Generated from Field `Booking`.`numberOfGuests` of type `Int!`)
  """
  numberOfGuests_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Booking`.`totalAmount` of type `Float!`
  """
  totalAmount: Float
  """
  ✨ `_expr` server value variant of `totalAmount` (✨ Generated from Field `Booking`.`totalAmount` of type `Float!`)
  """
  totalAmount_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `totalAmount` (✨ Generated from Field `Booking`.`totalAmount` of type `Float!`)
  """
  totalAmount_update: [Float_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Booking'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Booking_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Booking_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Booking_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Booking_Filter!]
  """
  ✨ Generated from Field `Booking`.`bookingId` of type `Int!`
  """
  bookingId: Int_Filter
  """
  ✨ Generated from Field `Booking`.`guestId` of type `Int!`
  """
  guestId: Int_Filter
  """
  ✨ Generated from Field `Booking`.`roomId` of type `Int!`
  """
  roomId: Int_Filter
  """
  ✨ Generated from Field `Booking`.`guest` of type `Guest!`
  """
  guest: Guest_Filter
  """
  ✨ Generated from Field `Booking`.`room` of type `Room!`
  """
  room: Room_Filter
  """
  ✨ Generated from Field `Booking`.`bookingDate` of type `Date!`
  """
  bookingDate: Date_Filter
  """
  ✨ Generated from Field `Booking`.`bookingStatus` of type `String!`
  """
  bookingStatus: String_Filter
  """
  ✨ Generated from Field `Booking`.`checkInDate` of type `Date!`
  """
  checkInDate: Date_Filter
  """
  ✨ Generated from Field `Booking`.`checkOutDate` of type `Date!`
  """
  checkOutDate: Date_Filter
  """
  ✨ Generated from Field `Booking`.`numberOfGuests` of type `Int!`
  """
  numberOfGuests: Int_Filter
  """
  ✨ Generated from Field `Booking`.`totalAmount` of type `Float!`
  """
  totalAmount: Float_Filter
  """
  ✨ Generated from Field `Booking`.`payments_on_booking` of type `[Payment!]!`
  """
  payments_on_booking: Payment_ListFilter
}
"""
✨ Generated first-row input type for table 'Booking'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Booking_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Booking_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Booking_Filter
}
"""
✨ Generated having input type for table 'Booking'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Booking_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Booking_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Booking_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Booking_Having!]
  """
  ✨ Generated from Field `Booking`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`bookingDate_count` of type `Int!`
  """
  bookingDate_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`bookingId_count` of type `Int!`
  """
  bookingId_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`bookingStatus_count` of type `Int!`
  """
  bookingStatus_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`checkInDate_count` of type `Int!`
  """
  checkInDate_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`checkOutDate_count` of type `Int!`
  """
  checkOutDate_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`guestId_count` of type `Int!`
  """
  guestId_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_count` of type `Int!`
  """
  numberOfGuests_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`roomId_count` of type `Int!`
  """
  roomId_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`totalAmount_count` of type `Int!`
  """
  totalAmount_count: Int_Filter
  """
  ✨ Generated from Field `Booking`.`bookingId_sum` of type `Int`
  """
  bookingId_sum: Int_Filter
  """
  ✨ Generated from Field `Booking`.`guestId_sum` of type `Int`
  """
  guestId_sum: Int_Filter
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_sum` of type `Int`
  """
  numberOfGuests_sum: Int_Filter
  """
  ✨ Generated from Field `Booking`.`roomId_sum` of type `Int`
  """
  roomId_sum: Int_Filter
  """
  ✨ Generated from Field `Booking`.`totalAmount_sum` of type `Float`
  """
  totalAmount_sum: Float_Filter
  """
  ✨ Generated from Field `Booking`.`bookingId_avg` of type `Float`
  """
  bookingId_avg: Float_Filter
  """
  ✨ Generated from Field `Booking`.`guestId_avg` of type `Float`
  """
  guestId_avg: Float_Filter
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_avg` of type `Float`
  """
  numberOfGuests_avg: Float_Filter
  """
  ✨ Generated from Field `Booking`.`roomId_avg` of type `Float`
  """
  roomId_avg: Float_Filter
  """
  ✨ Generated from Field `Booking`.`totalAmount_avg` of type `Float`
  """
  totalAmount_avg: Float_Filter
  """
  ✨ Generated from Field `Booking`.`bookingDate_min` of type `Date`
  """
  bookingDate_min: Date_Filter
  """
  ✨ Generated from Field `Booking`.`bookingId_min` of type `Int`
  """
  bookingId_min: Int_Filter
  """
  ✨ Generated from Field `Booking`.`checkInDate_min` of type `Date`
  """
  checkInDate_min: Date_Filter
  """
  ✨ Generated from Field `Booking`.`checkOutDate_min` of type `Date`
  """
  checkOutDate_min: Date_Filter
  """
  ✨ Generated from Field `Booking`.`guestId_min` of type `Int`
  """
  guestId_min: Int_Filter
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_min` of type `Int`
  """
  numberOfGuests_min: Int_Filter
  """
  ✨ Generated from Field `Booking`.`roomId_min` of type `Int`
  """
  roomId_min: Int_Filter
  """
  ✨ Generated from Field `Booking`.`totalAmount_min` of type `Float`
  """
  totalAmount_min: Float_Filter
  """
  ✨ Generated from Field `Booking`.`bookingDate_max` of type `Date`
  """
  bookingDate_max: Date_Filter
  """
  ✨ Generated from Field `Booking`.`bookingId_max` of type `Int`
  """
  bookingId_max: Int_Filter
  """
  ✨ Generated from Field `Booking`.`checkInDate_max` of type `Date`
  """
  checkInDate_max: Date_Filter
  """
  ✨ Generated from Field `Booking`.`checkOutDate_max` of type `Date`
  """
  checkOutDate_max: Date_Filter
  """
  ✨ Generated from Field `Booking`.`guestId_max` of type `Int`
  """
  guestId_max: Int_Filter
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_max` of type `Int`
  """
  numberOfGuests_max: Int_Filter
  """
  ✨ Generated from Field `Booking`.`roomId_max` of type `Int`
  """
  roomId_max: Int_Filter
  """
  ✨ Generated from Field `Booking`.`totalAmount_max` of type `Float`
  """
  totalAmount_max: Float_Filter
}
"""
✨ Generated key input type for table 'Booking'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Booking_Key {
  """
  ✨ Generated from Field `Booking`.`bookingId` of type `Int!`
  """
  bookingId: Int
  """
  ✨ `_expr` server value variant of `bookingId` (✨ Generated from Field `Booking`.`bookingId` of type `Int!`)
  """
  bookingId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Booking'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Booking_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Booking_Filter
}
"""
✨ Generated order input type for table 'Booking'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Booking_Order {
  """
  ✨ Generated from Field `Booking`.`bookingId` of type `Int!`
  """
  bookingId: OrderDirection
  """
  ✨ Generated from Field `Booking`.`guestId` of type `Int!`
  """
  guestId: OrderDirection
  """
  ✨ Generated from Field `Booking`.`roomId` of type `Int!`
  """
  roomId: OrderDirection
  """
  ✨ Generated from Field `Booking`.`guest` of type `Guest!`
  """
  guest: Guest_Order
  """
  ✨ Generated from Field `Booking`.`room` of type `Room!`
  """
  room: Room_Order
  """
  ✨ Generated from Field `Booking`.`bookingDate` of type `Date!`
  """
  bookingDate: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingStatus` of type `String!`
  """
  bookingStatus: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkInDate` of type `Date!`
  """
  checkInDate: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkOutDate` of type `Date!`
  """
  checkOutDate: OrderDirection
  """
  ✨ Generated from Field `Booking`.`numberOfGuests` of type `Int!`
  """
  numberOfGuests: OrderDirection
  """
  ✨ Generated from Field `Booking`.`totalAmount` of type `Float!`
  """
  totalAmount: OrderDirection
  """
  ✨ Generated from Field `Booking`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingDate_count` of type `Int!`
  """
  bookingDate_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingId_count` of type `Int!`
  """
  bookingId_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingStatus_count` of type `Int!`
  """
  bookingStatus_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkInDate_count` of type `Int!`
  """
  checkInDate_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkOutDate_count` of type `Int!`
  """
  checkOutDate_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`guestId_count` of type `Int!`
  """
  guestId_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_count` of type `Int!`
  """
  numberOfGuests_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`roomId_count` of type `Int!`
  """
  roomId_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`totalAmount_count` of type `Int!`
  """
  totalAmount_count: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingId_sum` of type `Int`
  """
  bookingId_sum: OrderDirection
  """
  ✨ Generated from Field `Booking`.`guestId_sum` of type `Int`
  """
  guestId_sum: OrderDirection
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_sum` of type `Int`
  """
  numberOfGuests_sum: OrderDirection
  """
  ✨ Generated from Field `Booking`.`roomId_sum` of type `Int`
  """
  roomId_sum: OrderDirection
  """
  ✨ Generated from Field `Booking`.`totalAmount_sum` of type `Float`
  """
  totalAmount_sum: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingId_avg` of type `Float`
  """
  bookingId_avg: OrderDirection
  """
  ✨ Generated from Field `Booking`.`guestId_avg` of type `Float`
  """
  guestId_avg: OrderDirection
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_avg` of type `Float`
  """
  numberOfGuests_avg: OrderDirection
  """
  ✨ Generated from Field `Booking`.`roomId_avg` of type `Float`
  """
  roomId_avg: OrderDirection
  """
  ✨ Generated from Field `Booking`.`totalAmount_avg` of type `Float`
  """
  totalAmount_avg: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingDate_min` of type `Date`
  """
  bookingDate_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingId_min` of type `Int`
  """
  bookingId_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkInDate_min` of type `Date`
  """
  checkInDate_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkOutDate_min` of type `Date`
  """
  checkOutDate_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`guestId_min` of type `Int`
  """
  guestId_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_min` of type `Int`
  """
  numberOfGuests_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`roomId_min` of type `Int`
  """
  roomId_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`totalAmount_min` of type `Float`
  """
  totalAmount_min: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingDate_max` of type `Date`
  """
  bookingDate_max: OrderDirection
  """
  ✨ Generated from Field `Booking`.`bookingId_max` of type `Int`
  """
  bookingId_max: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkInDate_max` of type `Date`
  """
  checkInDate_max: OrderDirection
  """
  ✨ Generated from Field `Booking`.`checkOutDate_max` of type `Date`
  """
  checkOutDate_max: OrderDirection
  """
  ✨ Generated from Field `Booking`.`guestId_max` of type `Int`
  """
  guestId_max: OrderDirection
  """
  ✨ Generated from Field `Booking`.`numberOfGuests_max` of type `Int`
  """
  numberOfGuests_max: OrderDirection
  """
  ✨ Generated from Field `Booking`.`roomId_max` of type `Int`
  """
  roomId_max: OrderDirection
  """
  ✨ Generated from Field `Booking`.`totalAmount_max` of type `Float`
  """
  totalAmount_max: OrderDirection
}
"""
✨ Generated data input type for table 'Employee'. It includes all necessary fields for creating or upserting rows into table.
"""
input Employee_Data {
  """
  ✨ Generated from Field `Employee`.`employeeId` of type `Int!`
  """
  employeeId: Int
  """
  ✨ `_expr` server value variant of `employeeId` (✨ Generated from Field `Employee`.`employeeId` of type `Int!`)
  """
  employeeId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `employeeId` (✨ Generated from Field `Employee`.`employeeId` of type `Int!`)
  """
  employeeId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`hotelId` of type `Int!`
  """
  hotelId: Int
  """
  ✨ `_expr` server value variant of `hotelId` (✨ Generated from Field `Employee`.`hotelId` of type `Int!`)
  """
  hotelId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `hotelId` (✨ Generated from Field `Employee`.`hotelId` of type `Int!`)
  """
  hotelId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`jobTypeId` of type `Int!`
  """
  jobTypeId: Int
  """
  ✨ `_expr` server value variant of `jobTypeId` (✨ Generated from Field `Employee`.`jobTypeId` of type `Int!`)
  """
  jobTypeId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `jobTypeId` (✨ Generated from Field `Employee`.`jobTypeId` of type `Int!`)
  """
  jobTypeId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`hotel` of type `Hotel!`
  """
  hotel: Hotel_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`jobType` of type `JobType!`
  """
  jobType: JobType_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `Employee`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`firstName` of type `String!`
  """
  firstName: String
  """
  ✨ `_expr` server value variant of `firstName` (✨ Generated from Field `Employee`.`firstName` of type `String!`)
  """
  firstName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`hireDate` of type `Date!`
  """
  hireDate: Date
  """
  ✨ `_date` server value variant of `hireDate` (✨ Generated from Field `Employee`.`hireDate` of type `Date!`)
  """
  hireDate_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `hireDate` (✨ Generated from Field `Employee`.`hireDate` of type `Date!`)
  """
  hireDate_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `hireDate` (✨ Generated from Field `Employee`.`hireDate` of type `Date!`)
  """
  hireDate_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`lastName` of type `String!`
  """
  lastName: String
  """
  ✨ `_expr` server value variant of `lastName` (✨ Generated from Field `Employee`.`lastName` of type `String!`)
  """
  lastName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`phoneNumber` of type `String!`
  """
  phoneNumber: String
  """
  ✨ `_expr` server value variant of `phoneNumber` (✨ Generated from Field `Employee`.`phoneNumber` of type `String!`)
  """
  phoneNumber_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Employee`.`salary` of type `Float`
  """
  salary: Float
  """
  ✨ `_expr` server value variant of `salary` (✨ Generated from Field `Employee`.`salary` of type `Float`)
  """
  salary_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `salary` (✨ Generated from Field `Employee`.`salary` of type `Float`)
  """
  salary_update: [Float_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Employee'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Employee_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Employee_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Employee_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Employee_Filter!]
  """
  ✨ Generated from Field `Employee`.`employeeId` of type `Int!`
  """
  employeeId: Int_Filter
  """
  ✨ Generated from Field `Employee`.`hotelId` of type `Int!`
  """
  hotelId: Int_Filter
  """
  ✨ Generated from Field `Employee`.`jobTypeId` of type `Int!`
  """
  jobTypeId: Int_Filter
  """
  ✨ Generated from Field `Employee`.`hotel` of type `Hotel!`
  """
  hotel: Hotel_Filter
  """
  ✨ Generated from Field `Employee`.`jobType` of type `JobType!`
  """
  jobType: JobType_Filter
  """
  ✨ Generated from Field `Employee`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `Employee`.`firstName` of type `String!`
  """
  firstName: String_Filter
  """
  ✨ Generated from Field `Employee`.`hireDate` of type `Date!`
  """
  hireDate: Date_Filter
  """
  ✨ Generated from Field `Employee`.`lastName` of type `String!`
  """
  lastName: String_Filter
  """
  ✨ Generated from Field `Employee`.`phoneNumber` of type `String!`
  """
  phoneNumber: String_Filter
  """
  ✨ Generated from Field `Employee`.`salary` of type `Float`
  """
  salary: Float_Filter
}
"""
✨ Generated first-row input type for table 'Employee'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Employee_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Employee_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Employee_Filter
}
"""
✨ Generated having input type for table 'Employee'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Employee_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Employee_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Employee_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Employee_Having!]
  """
  ✨ Generated from Field `Employee`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`employeeId_count` of type `Int!`
  """
  employeeId_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`firstName_count` of type `Int!`
  """
  firstName_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`hireDate_count` of type `Int!`
  """
  hireDate_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`hotelId_count` of type `Int!`
  """
  hotelId_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`jobTypeId_count` of type `Int!`
  """
  jobTypeId_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`lastName_count` of type `Int!`
  """
  lastName_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`salary_count` of type `Int!`
  """
  salary_count: Int_Filter
  """
  ✨ Generated from Field `Employee`.`employeeId_sum` of type `Int`
  """
  employeeId_sum: Int_Filter
  """
  ✨ Generated from Field `Employee`.`hotelId_sum` of type `Int`
  """
  hotelId_sum: Int_Filter
  """
  ✨ Generated from Field `Employee`.`jobTypeId_sum` of type `Int`
  """
  jobTypeId_sum: Int_Filter
  """
  ✨ Generated from Field `Employee`.`salary_sum` of type `Float`
  """
  salary_sum: Float_Filter
  """
  ✨ Generated from Field `Employee`.`employeeId_avg` of type `Float`
  """
  employeeId_avg: Float_Filter
  """
  ✨ Generated from Field `Employee`.`hotelId_avg` of type `Float`
  """
  hotelId_avg: Float_Filter
  """
  ✨ Generated from Field `Employee`.`jobTypeId_avg` of type `Float`
  """
  jobTypeId_avg: Float_Filter
  """
  ✨ Generated from Field `Employee`.`salary_avg` of type `Float`
  """
  salary_avg: Float_Filter
  """
  ✨ Generated from Field `Employee`.`employeeId_min` of type `Int`
  """
  employeeId_min: Int_Filter
  """
  ✨ Generated from Field `Employee`.`hireDate_min` of type `Date`
  """
  hireDate_min: Date_Filter
  """
  ✨ Generated from Field `Employee`.`hotelId_min` of type `Int`
  """
  hotelId_min: Int_Filter
  """
  ✨ Generated from Field `Employee`.`jobTypeId_min` of type `Int`
  """
  jobTypeId_min: Int_Filter
  """
  ✨ Generated from Field `Employee`.`salary_min` of type `Float`
  """
  salary_min: Float_Filter
  """
  ✨ Generated from Field `Employee`.`employeeId_max` of type `Int`
  """
  employeeId_max: Int_Filter
  """
  ✨ Generated from Field `Employee`.`hireDate_max` of type `Date`
  """
  hireDate_max: Date_Filter
  """
  ✨ Generated from Field `Employee`.`hotelId_max` of type `Int`
  """
  hotelId_max: Int_Filter
  """
  ✨ Generated from Field `Employee`.`jobTypeId_max` of type `Int`
  """
  jobTypeId_max: Int_Filter
  """
  ✨ Generated from Field `Employee`.`salary_max` of type `Float`
  """
  salary_max: Float_Filter
}
"""
✨ Generated key input type for table 'Employee'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Employee_Key {
  """
  ✨ Generated from Field `Employee`.`employeeId` of type `Int!`
  """
  employeeId: Int
  """
  ✨ `_expr` server value variant of `employeeId` (✨ Generated from Field `Employee`.`employeeId` of type `Int!`)
  """
  employeeId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Employee'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Employee_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Employee_Filter
}
"""
✨ Generated order input type for table 'Employee'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Employee_Order {
  """
  ✨ Generated from Field `Employee`.`employeeId` of type `Int!`
  """
  employeeId: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hotelId` of type `Int!`
  """
  hotelId: OrderDirection
  """
  ✨ Generated from Field `Employee`.`jobTypeId` of type `Int!`
  """
  jobTypeId: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hotel` of type `Hotel!`
  """
  hotel: Hotel_Order
  """
  ✨ Generated from Field `Employee`.`jobType` of type `JobType!`
  """
  jobType: JobType_Order
  """
  ✨ Generated from Field `Employee`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `Employee`.`firstName` of type `String!`
  """
  firstName: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hireDate` of type `Date!`
  """
  hireDate: OrderDirection
  """
  ✨ Generated from Field `Employee`.`lastName` of type `String!`
  """
  lastName: OrderDirection
  """
  ✨ Generated from Field `Employee`.`phoneNumber` of type `String!`
  """
  phoneNumber: OrderDirection
  """
  ✨ Generated from Field `Employee`.`salary` of type `Float`
  """
  salary: OrderDirection
  """
  ✨ Generated from Field `Employee`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`employeeId_count` of type `Int!`
  """
  employeeId_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`firstName_count` of type `Int!`
  """
  firstName_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hireDate_count` of type `Int!`
  """
  hireDate_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hotelId_count` of type `Int!`
  """
  hotelId_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`jobTypeId_count` of type `Int!`
  """
  jobTypeId_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`lastName_count` of type `Int!`
  """
  lastName_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`salary_count` of type `Int!`
  """
  salary_count: OrderDirection
  """
  ✨ Generated from Field `Employee`.`employeeId_sum` of type `Int`
  """
  employeeId_sum: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hotelId_sum` of type `Int`
  """
  hotelId_sum: OrderDirection
  """
  ✨ Generated from Field `Employee`.`jobTypeId_sum` of type `Int`
  """
  jobTypeId_sum: OrderDirection
  """
  ✨ Generated from Field `Employee`.`salary_sum` of type `Float`
  """
  salary_sum: OrderDirection
  """
  ✨ Generated from Field `Employee`.`employeeId_avg` of type `Float`
  """
  employeeId_avg: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hotelId_avg` of type `Float`
  """
  hotelId_avg: OrderDirection
  """
  ✨ Generated from Field `Employee`.`jobTypeId_avg` of type `Float`
  """
  jobTypeId_avg: OrderDirection
  """
  ✨ Generated from Field `Employee`.`salary_avg` of type `Float`
  """
  salary_avg: OrderDirection
  """
  ✨ Generated from Field `Employee`.`employeeId_min` of type `Int`
  """
  employeeId_min: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hireDate_min` of type `Date`
  """
  hireDate_min: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hotelId_min` of type `Int`
  """
  hotelId_min: OrderDirection
  """
  ✨ Generated from Field `Employee`.`jobTypeId_min` of type `Int`
  """
  jobTypeId_min: OrderDirection
  """
  ✨ Generated from Field `Employee`.`salary_min` of type `Float`
  """
  salary_min: OrderDirection
  """
  ✨ Generated from Field `Employee`.`employeeId_max` of type `Int`
  """
  employeeId_max: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hireDate_max` of type `Date`
  """
  hireDate_max: OrderDirection
  """
  ✨ Generated from Field `Employee`.`hotelId_max` of type `Int`
  """
  hotelId_max: OrderDirection
  """
  ✨ Generated from Field `Employee`.`jobTypeId_max` of type `Int`
  """
  jobTypeId_max: OrderDirection
  """
  ✨ Generated from Field `Employee`.`salary_max` of type `Float`
  """
  salary_max: OrderDirection
}
"""
✨ Generated data input type for table 'Guest'. It includes all necessary fields for creating or upserting rows into table.
"""
input Guest_Data {
  """
  ✨ Generated from Field `Guest`.`guestId` of type `Int!`
  """
  guestId: Int
  """
  ✨ `_expr` server value variant of `guestId` (✨ Generated from Field `Guest`.`guestId` of type `Int!`)
  """
  guestId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `guestId` (✨ Generated from Field `Guest`.`guestId` of type `Int!`)
  """
  guestId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Guest`.`address` of type `String`
  """
  address: String
  """
  ✨ `_expr` server value variant of `address` (✨ Generated from Field `Guest`.`address` of type `String`)
  """
  address_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Guest`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `Guest`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Guest`.`firstName` of type `String!`
  """
  firstName: String
  """
  ✨ `_expr` server value variant of `firstName` (✨ Generated from Field `Guest`.`firstName` of type `String!`)
  """
  firstName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Guest`.`lastName` of type `String!`
  """
  lastName: String
  """
  ✨ `_expr` server value variant of `lastName` (✨ Generated from Field `Guest`.`lastName` of type `String!`)
  """
  lastName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Guest`.`nationalIdOrPassport` of type `String!`
  """
  nationalIdOrPassport: String
  """
  ✨ `_expr` server value variant of `nationalIdOrPassport` (✨ Generated from Field `Guest`.`nationalIdOrPassport` of type `String!`)
  """
  nationalIdOrPassport_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Guest`.`phoneNumber` of type `String!`
  """
  phoneNumber: String
  """
  ✨ `_expr` server value variant of `phoneNumber` (✨ Generated from Field `Guest`.`phoneNumber` of type `String!`)
  """
  phoneNumber_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Guest'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Guest_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Guest_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Guest_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Guest_Filter!]
  """
  ✨ Generated from Field `Guest`.`guestId` of type `Int!`
  """
  guestId: Int_Filter
  """
  ✨ Generated from Field `Guest`.`address` of type `String`
  """
  address: String_Filter
  """
  ✨ Generated from Field `Guest`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `Guest`.`firstName` of type `String!`
  """
  firstName: String_Filter
  """
  ✨ Generated from Field `Guest`.`lastName` of type `String!`
  """
  lastName: String_Filter
  """
  ✨ Generated from Field `Guest`.`nationalIdOrPassport` of type `String!`
  """
  nationalIdOrPassport: String_Filter
  """
  ✨ Generated from Field `Guest`.`phoneNumber` of type `String!`
  """
  phoneNumber: String_Filter
  """
  ✨ Generated from Field `Guest`.`bookings_on_guest` of type `[Booking!]!`
  """
  bookings_on_guest: Booking_ListFilter
}
"""
✨ Generated first-row input type for table 'Guest'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Guest_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Guest_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Guest_Filter
}
"""
✨ Generated having input type for table 'Guest'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Guest_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Guest_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Guest_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Guest_Having!]
  """
  ✨ Generated from Field `Guest`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`address_count` of type `Int!`
  """
  address_count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`firstName_count` of type `Int!`
  """
  firstName_count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`guestId_count` of type `Int!`
  """
  guestId_count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`lastName_count` of type `Int!`
  """
  lastName_count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`nationalIdOrPassport_count` of type `Int!`
  """
  nationalIdOrPassport_count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: Int_Filter
  """
  ✨ Generated from Field `Guest`.`guestId_sum` of type `Int`
  """
  guestId_sum: Int_Filter
  """
  ✨ Generated from Field `Guest`.`guestId_avg` of type `Float`
  """
  guestId_avg: Float_Filter
  """
  ✨ Generated from Field `Guest`.`guestId_min` of type `Int`
  """
  guestId_min: Int_Filter
  """
  ✨ Generated from Field `Guest`.`guestId_max` of type `Int`
  """
  guestId_max: Int_Filter
}
"""
✨ Generated key input type for table 'Guest'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Guest_Key {
  """
  ✨ Generated from Field `Guest`.`guestId` of type `Int!`
  """
  guestId: Int
  """
  ✨ `_expr` server value variant of `guestId` (✨ Generated from Field `Guest`.`guestId` of type `Int!`)
  """
  guestId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Guest'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Guest_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Guest_Filter
}
"""
✨ Generated order input type for table 'Guest'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Guest_Order {
  """
  ✨ Generated from Field `Guest`.`guestId` of type `Int!`
  """
  guestId: OrderDirection
  """
  ✨ Generated from Field `Guest`.`address` of type `String`
  """
  address: OrderDirection
  """
  ✨ Generated from Field `Guest`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `Guest`.`firstName` of type `String!`
  """
  firstName: OrderDirection
  """
  ✨ Generated from Field `Guest`.`lastName` of type `String!`
  """
  lastName: OrderDirection
  """
  ✨ Generated from Field `Guest`.`nationalIdOrPassport` of type `String!`
  """
  nationalIdOrPassport: OrderDirection
  """
  ✨ Generated from Field `Guest`.`phoneNumber` of type `String!`
  """
  phoneNumber: OrderDirection
  """
  ✨ Generated from Field `Guest`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`address_count` of type `Int!`
  """
  address_count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`firstName_count` of type `Int!`
  """
  firstName_count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`guestId_count` of type `Int!`
  """
  guestId_count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`lastName_count` of type `Int!`
  """
  lastName_count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`nationalIdOrPassport_count` of type `Int!`
  """
  nationalIdOrPassport_count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: OrderDirection
  """
  ✨ Generated from Field `Guest`.`guestId_sum` of type `Int`
  """
  guestId_sum: OrderDirection
  """
  ✨ Generated from Field `Guest`.`guestId_avg` of type `Float`
  """
  guestId_avg: OrderDirection
  """
  ✨ Generated from Field `Guest`.`guestId_min` of type `Int`
  """
  guestId_min: OrderDirection
  """
  ✨ Generated from Field `Guest`.`guestId_max` of type `Int`
  """
  guestId_max: OrderDirection
}
"""
✨ Generated data input type for table 'Hotel'. It includes all necessary fields for creating or upserting rows into table.
"""
input Hotel_Data {
  """
  ✨ Generated from Field `Hotel`.`hotelId` of type `Int!`
  """
  hotelId: Int
  """
  ✨ `_expr` server value variant of `hotelId` (✨ Generated from Field `Hotel`.`hotelId` of type `Int!`)
  """
  hotelId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `hotelId` (✨ Generated from Field `Hotel`.`hotelId` of type `Int!`)
  """
  hotelId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`address` of type `String!`
  """
  address: String
  """
  ✨ `_expr` server value variant of `address` (✨ Generated from Field `Hotel`.`address` of type `String!`)
  """
  address_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`city` of type `String!`
  """
  city: String
  """
  ✨ `_expr` server value variant of `city` (✨ Generated from Field `Hotel`.`city` of type `String!`)
  """
  city_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`email` of type `String!`
  """
  email: String
  """
  ✨ `_expr` server value variant of `email` (✨ Generated from Field `Hotel`.`email` of type `String!`)
  """
  email_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`hotelName` of type `String!`
  """
  hotelName: String
  """
  ✨ `_expr` server value variant of `hotelName` (✨ Generated from Field `Hotel`.`hotelName` of type `String!`)
  """
  hotelName_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`phoneNumber` of type `String!`
  """
  phoneNumber: String
  """
  ✨ `_expr` server value variant of `phoneNumber` (✨ Generated from Field `Hotel`.`phoneNumber` of type `String!`)
  """
  phoneNumber_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Hotel`.`rating` of type `Float`
  """
  rating: Float
  """
  ✨ `_expr` server value variant of `rating` (✨ Generated from Field `Hotel`.`rating` of type `Float`)
  """
  rating_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `rating` (✨ Generated from Field `Hotel`.`rating` of type `Float`)
  """
  rating_update: [Float_Update!] @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Hotel'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Hotel_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Hotel_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Hotel_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Hotel_Filter!]
  """
  ✨ Generated from Field `Hotel`.`hotelId` of type `Int!`
  """
  hotelId: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`address` of type `String!`
  """
  address: String_Filter
  """
  ✨ Generated from Field `Hotel`.`city` of type `String!`
  """
  city: String_Filter
  """
  ✨ Generated from Field `Hotel`.`email` of type `String!`
  """
  email: String_Filter
  """
  ✨ Generated from Field `Hotel`.`hotelName` of type `String!`
  """
  hotelName: String_Filter
  """
  ✨ Generated from Field `Hotel`.`phoneNumber` of type `String!`
  """
  phoneNumber: String_Filter
  """
  ✨ Generated from Field `Hotel`.`rating` of type `Float`
  """
  rating: Float_Filter
  """
  ✨ Generated from Field `Hotel`.`employees_on_hotel` of type `[Employee!]!`
  """
  employees_on_hotel: Employee_ListFilter
  """
  ✨ Generated from Field `Hotel`.`rooms_on_hotel` of type `[Room!]!`
  """
  rooms_on_hotel: Room_ListFilter
}
"""
✨ Generated first-row input type for table 'Hotel'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Hotel_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Hotel_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Hotel_Filter
}
"""
✨ Generated having input type for table 'Hotel'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Hotel_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Hotel_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Hotel_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Hotel_Having!]
  """
  ✨ Generated from Field `Hotel`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`address_count` of type `Int!`
  """
  address_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`city_count` of type `Int!`
  """
  city_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`email_count` of type `Int!`
  """
  email_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`hotelId_count` of type `Int!`
  """
  hotelId_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`hotelName_count` of type `Int!`
  """
  hotelName_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`rating_count` of type `Int!`
  """
  rating_count: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`hotelId_sum` of type `Int`
  """
  hotelId_sum: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`rating_sum` of type `Float`
  """
  rating_sum: Float_Filter
  """
  ✨ Generated from Field `Hotel`.`hotelId_avg` of type `Float`
  """
  hotelId_avg: Float_Filter
  """
  ✨ Generated from Field `Hotel`.`rating_avg` of type `Float`
  """
  rating_avg: Float_Filter
  """
  ✨ Generated from Field `Hotel`.`hotelId_min` of type `Int`
  """
  hotelId_min: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`rating_min` of type `Float`
  """
  rating_min: Float_Filter
  """
  ✨ Generated from Field `Hotel`.`hotelId_max` of type `Int`
  """
  hotelId_max: Int_Filter
  """
  ✨ Generated from Field `Hotel`.`rating_max` of type `Float`
  """
  rating_max: Float_Filter
}
"""
✨ Generated key input type for table 'Hotel'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Hotel_Key {
  """
  ✨ Generated from Field `Hotel`.`hotelId` of type `Int!`
  """
  hotelId: Int
  """
  ✨ `_expr` server value variant of `hotelId` (✨ Generated from Field `Hotel`.`hotelId` of type `Int!`)
  """
  hotelId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Hotel'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Hotel_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Hotel_Filter
}
"""
✨ Generated order input type for table 'Hotel'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Hotel_Order {
  """
  ✨ Generated from Field `Hotel`.`hotelId` of type `Int!`
  """
  hotelId: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`address` of type `String!`
  """
  address: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`city` of type `String!`
  """
  city: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`email` of type `String!`
  """
  email: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`hotelName` of type `String!`
  """
  hotelName: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`phoneNumber` of type `String!`
  """
  phoneNumber: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`rating` of type `Float`
  """
  rating: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`address_count` of type `Int!`
  """
  address_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`city_count` of type `Int!`
  """
  city_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`email_count` of type `Int!`
  """
  email_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`hotelId_count` of type `Int!`
  """
  hotelId_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`hotelName_count` of type `Int!`
  """
  hotelName_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`phoneNumber_count` of type `Int!`
  """
  phoneNumber_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`rating_count` of type `Int!`
  """
  rating_count: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`hotelId_sum` of type `Int`
  """
  hotelId_sum: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`rating_sum` of type `Float`
  """
  rating_sum: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`hotelId_avg` of type `Float`
  """
  hotelId_avg: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`rating_avg` of type `Float`
  """
  rating_avg: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`hotelId_min` of type `Int`
  """
  hotelId_min: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`rating_min` of type `Float`
  """
  rating_min: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`hotelId_max` of type `Int`
  """
  hotelId_max: OrderDirection
  """
  ✨ Generated from Field `Hotel`.`rating_max` of type `Float`
  """
  rating_max: OrderDirection
}
"""
✨ Generated data input type for table 'JobType'. It includes all necessary fields for creating or upserting rows into table.
"""
input JobType_Data {
  """
  ✨ Generated from Field `JobType`.`jobTypeId` of type `Int!`
  """
  jobTypeId: Int
  """
  ✨ `_expr` server value variant of `jobTypeId` (✨ Generated from Field `JobType`.`jobTypeId` of type `Int!`)
  """
  jobTypeId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `jobTypeId` (✨ Generated from Field `JobType`.`jobTypeId` of type `Int!`)
  """
  jobTypeId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `JobType`.`department` of type `String!`
  """
  department: String
  """
  ✨ `_expr` server value variant of `department` (✨ Generated from Field `JobType`.`department` of type `String!`)
  """
  department_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `JobType`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `JobType`.`description` of type `String`)
  """
  description_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `JobType`.`jobTitle` of type `String!`
  """
  jobTitle: String
  """
  ✨ `_expr` server value variant of `jobTitle` (✨ Generated from Field `JobType`.`jobTitle` of type `String!`)
  """
  jobTitle_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'JobType'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input JobType_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [JobType_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: JobType_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [JobType_Filter!]
  """
  ✨ Generated from Field `JobType`.`jobTypeId` of type `Int!`
  """
  jobTypeId: Int_Filter
  """
  ✨ Generated from Field `JobType`.`department` of type `String!`
  """
  department: String_Filter
  """
  ✨ Generated from Field `JobType`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `JobType`.`jobTitle` of type `String!`
  """
  jobTitle: String_Filter
  """
  ✨ Generated from Field `JobType`.`employees_on_jobType` of type `[Employee!]!`
  """
  employees_on_jobType: Employee_ListFilter
}
"""
✨ Generated first-row input type for table 'JobType'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input JobType_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [JobType_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: JobType_Filter
}
"""
✨ Generated having input type for table 'JobType'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input JobType_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [JobType_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: JobType_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [JobType_Having!]
  """
  ✨ Generated from Field `JobType`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `JobType`.`department_count` of type `Int!`
  """
  department_count: Int_Filter
  """
  ✨ Generated from Field `JobType`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `JobType`.`jobTitle_count` of type `Int!`
  """
  jobTitle_count: Int_Filter
  """
  ✨ Generated from Field `JobType`.`jobTypeId_count` of type `Int!`
  """
  jobTypeId_count: Int_Filter
  """
  ✨ Generated from Field `JobType`.`jobTypeId_sum` of type `Int`
  """
  jobTypeId_sum: Int_Filter
  """
  ✨ Generated from Field `JobType`.`jobTypeId_avg` of type `Float`
  """
  jobTypeId_avg: Float_Filter
  """
  ✨ Generated from Field `JobType`.`jobTypeId_min` of type `Int`
  """
  jobTypeId_min: Int_Filter
  """
  ✨ Generated from Field `JobType`.`jobTypeId_max` of type `Int`
  """
  jobTypeId_max: Int_Filter
}
"""
✨ Generated key input type for table 'JobType'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input JobType_Key {
  """
  ✨ Generated from Field `JobType`.`jobTypeId` of type `Int!`
  """
  jobTypeId: Int
  """
  ✨ `_expr` server value variant of `jobTypeId` (✨ Generated from Field `JobType`.`jobTypeId` of type `Int!`)
  """
  jobTypeId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'JobType'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input JobType_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: JobType_Filter
}
"""
✨ Generated order input type for table 'JobType'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input JobType_Order {
  """
  ✨ Generated from Field `JobType`.`jobTypeId` of type `Int!`
  """
  jobTypeId: OrderDirection
  """
  ✨ Generated from Field `JobType`.`department` of type `String!`
  """
  department: OrderDirection
  """
  ✨ Generated from Field `JobType`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `JobType`.`jobTitle` of type `String!`
  """
  jobTitle: OrderDirection
  """
  ✨ Generated from Field `JobType`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `JobType`.`department_count` of type `Int!`
  """
  department_count: OrderDirection
  """
  ✨ Generated from Field `JobType`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `JobType`.`jobTitle_count` of type `Int!`
  """
  jobTitle_count: OrderDirection
  """
  ✨ Generated from Field `JobType`.`jobTypeId_count` of type `Int!`
  """
  jobTypeId_count: OrderDirection
  """
  ✨ Generated from Field `JobType`.`jobTypeId_sum` of type `Int`
  """
  jobTypeId_sum: OrderDirection
  """
  ✨ Generated from Field `JobType`.`jobTypeId_avg` of type `Float`
  """
  jobTypeId_avg: OrderDirection
  """
  ✨ Generated from Field `JobType`.`jobTypeId_min` of type `Int`
  """
  jobTypeId_min: OrderDirection
  """
  ✨ Generated from Field `JobType`.`jobTypeId_max` of type `Int`
  """
  jobTypeId_max: OrderDirection
}
"""
✨ Generated data input type for table 'Payment'. It includes all necessary fields for creating or upserting rows into table.
"""
input Payment_Data {
  """
  ✨ Generated from Field `Payment`.`paymentId` of type `Int!`
  """
  paymentId: Int
  """
  ✨ `_expr` server value variant of `paymentId` (✨ Generated from Field `Payment`.`paymentId` of type `Int!`)
  """
  paymentId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `paymentId` (✨ Generated from Field `Payment`.`paymentId` of type `Int!`)
  """
  paymentId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Payment`.`bookingId` of type `Int!`
  """
  bookingId: Int
  """
  ✨ `_expr` server value variant of `bookingId` (✨ Generated from Field `Payment`.`bookingId` of type `Int!`)
  """
  bookingId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `bookingId` (✨ Generated from Field `Payment`.`bookingId` of type `Int!`)
  """
  bookingId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Payment`.`booking` of type `Booking!`
  """
  booking: Booking_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Payment`.`amount` of type `Float!`
  """
  amount: Float
  """
  ✨ `_expr` server value variant of `amount` (✨ Generated from Field `Payment`.`amount` of type `Float!`)
  """
  amount_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `amount` (✨ Generated from Field `Payment`.`amount` of type `Float!`)
  """
  amount_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Payment`.`paymentDate` of type `Date!`
  """
  paymentDate: Date
  """
  ✨ `_date` server value variant of `paymentDate` (✨ Generated from Field `Payment`.`paymentDate` of type `Date!`)
  """
  paymentDate_date: Date_Relative @fdc_forbiddenInVariables
  """
  ✨ `_expr` server value variant of `paymentDate` (✨ Generated from Field `Payment`.`paymentDate` of type `Date!`)
  """
  paymentDate_expr: Date_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `paymentDate` (✨ Generated from Field `Payment`.`paymentDate` of type `Date!`)
  """
  paymentDate_update: [Date_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Payment`.`paymentMethod` of type `String!`
  """
  paymentMethod: String
  """
  ✨ `_expr` server value variant of `paymentMethod` (✨ Generated from Field `Payment`.`paymentMethod` of type `String!`)
  """
  paymentMethod_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Payment`.`paymentStatus` of type `String!`
  """
  paymentStatus: String
  """
  ✨ `_expr` server value variant of `paymentStatus` (✨ Generated from Field `Payment`.`paymentStatus` of type `String!`)
  """
  paymentStatus_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Payment`.`transactionReference` of type `String`
  """
  transactionReference: String
  """
  ✨ `_expr` server value variant of `transactionReference` (✨ Generated from Field `Payment`.`transactionReference` of type `String`)
  """
  transactionReference_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Payment'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Payment_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Payment_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Payment_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Payment_Filter!]
  """
  ✨ Generated from Field `Payment`.`paymentId` of type `Int!`
  """
  paymentId: Int_Filter
  """
  ✨ Generated from Field `Payment`.`bookingId` of type `Int!`
  """
  bookingId: Int_Filter
  """
  ✨ Generated from Field `Payment`.`booking` of type `Booking!`
  """
  booking: Booking_Filter
  """
  ✨ Generated from Field `Payment`.`amount` of type `Float!`
  """
  amount: Float_Filter
  """
  ✨ Generated from Field `Payment`.`paymentDate` of type `Date!`
  """
  paymentDate: Date_Filter
  """
  ✨ Generated from Field `Payment`.`paymentMethod` of type `String!`
  """
  paymentMethod: String_Filter
  """
  ✨ Generated from Field `Payment`.`paymentStatus` of type `String!`
  """
  paymentStatus: String_Filter
  """
  ✨ Generated from Field `Payment`.`transactionReference` of type `String`
  """
  transactionReference: String_Filter
}
"""
✨ Generated first-row input type for table 'Payment'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Payment_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Payment_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Payment_Filter
}
"""
✨ Generated having input type for table 'Payment'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Payment_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Payment_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Payment_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Payment_Having!]
  """
  ✨ Generated from Field `Payment`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`amount_count` of type `Int!`
  """
  amount_count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`bookingId_count` of type `Int!`
  """
  bookingId_count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`paymentDate_count` of type `Int!`
  """
  paymentDate_count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`paymentId_count` of type `Int!`
  """
  paymentId_count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`paymentMethod_count` of type `Int!`
  """
  paymentMethod_count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`paymentStatus_count` of type `Int!`
  """
  paymentStatus_count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`transactionReference_count` of type `Int!`
  """
  transactionReference_count: Int_Filter
  """
  ✨ Generated from Field `Payment`.`amount_sum` of type `Float`
  """
  amount_sum: Float_Filter
  """
  ✨ Generated from Field `Payment`.`bookingId_sum` of type `Int`
  """
  bookingId_sum: Int_Filter
  """
  ✨ Generated from Field `Payment`.`paymentId_sum` of type `Int`
  """
  paymentId_sum: Int_Filter
  """
  ✨ Generated from Field `Payment`.`amount_avg` of type `Float`
  """
  amount_avg: Float_Filter
  """
  ✨ Generated from Field `Payment`.`bookingId_avg` of type `Float`
  """
  bookingId_avg: Float_Filter
  """
  ✨ Generated from Field `Payment`.`paymentId_avg` of type `Float`
  """
  paymentId_avg: Float_Filter
  """
  ✨ Generated from Field `Payment`.`amount_min` of type `Float`
  """
  amount_min: Float_Filter
  """
  ✨ Generated from Field `Payment`.`bookingId_min` of type `Int`
  """
  bookingId_min: Int_Filter
  """
  ✨ Generated from Field `Payment`.`paymentDate_min` of type `Date`
  """
  paymentDate_min: Date_Filter
  """
  ✨ Generated from Field `Payment`.`paymentId_min` of type `Int`
  """
  paymentId_min: Int_Filter
  """
  ✨ Generated from Field `Payment`.`amount_max` of type `Float`
  """
  amount_max: Float_Filter
  """
  ✨ Generated from Field `Payment`.`bookingId_max` of type `Int`
  """
  bookingId_max: Int_Filter
  """
  ✨ Generated from Field `Payment`.`paymentDate_max` of type `Date`
  """
  paymentDate_max: Date_Filter
  """
  ✨ Generated from Field `Payment`.`paymentId_max` of type `Int`
  """
  paymentId_max: Int_Filter
}
"""
✨ Generated key input type for table 'Payment'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Payment_Key {
  """
  ✨ Generated from Field `Payment`.`paymentId` of type `Int!`
  """
  paymentId: Int
  """
  ✨ `_expr` server value variant of `paymentId` (✨ Generated from Field `Payment`.`paymentId` of type `Int!`)
  """
  paymentId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Payment'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Payment_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Payment_Filter
}
"""
✨ Generated order input type for table 'Payment'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Payment_Order {
  """
  ✨ Generated from Field `Payment`.`paymentId` of type `Int!`
  """
  paymentId: OrderDirection
  """
  ✨ Generated from Field `Payment`.`bookingId` of type `Int!`
  """
  bookingId: OrderDirection
  """
  ✨ Generated from Field `Payment`.`booking` of type `Booking!`
  """
  booking: Booking_Order
  """
  ✨ Generated from Field `Payment`.`amount` of type `Float!`
  """
  amount: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentDate` of type `Date!`
  """
  paymentDate: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentMethod` of type `String!`
  """
  paymentMethod: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentStatus` of type `String!`
  """
  paymentStatus: OrderDirection
  """
  ✨ Generated from Field `Payment`.`transactionReference` of type `String`
  """
  transactionReference: OrderDirection
  """
  ✨ Generated from Field `Payment`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`amount_count` of type `Int!`
  """
  amount_count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`bookingId_count` of type `Int!`
  """
  bookingId_count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentDate_count` of type `Int!`
  """
  paymentDate_count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentId_count` of type `Int!`
  """
  paymentId_count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentMethod_count` of type `Int!`
  """
  paymentMethod_count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentStatus_count` of type `Int!`
  """
  paymentStatus_count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`transactionReference_count` of type `Int!`
  """
  transactionReference_count: OrderDirection
  """
  ✨ Generated from Field `Payment`.`amount_sum` of type `Float`
  """
  amount_sum: OrderDirection
  """
  ✨ Generated from Field `Payment`.`bookingId_sum` of type `Int`
  """
  bookingId_sum: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentId_sum` of type `Int`
  """
  paymentId_sum: OrderDirection
  """
  ✨ Generated from Field `Payment`.`amount_avg` of type `Float`
  """
  amount_avg: OrderDirection
  """
  ✨ Generated from Field `Payment`.`bookingId_avg` of type `Float`
  """
  bookingId_avg: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentId_avg` of type `Float`
  """
  paymentId_avg: OrderDirection
  """
  ✨ Generated from Field `Payment`.`amount_min` of type `Float`
  """
  amount_min: OrderDirection
  """
  ✨ Generated from Field `Payment`.`bookingId_min` of type `Int`
  """
  bookingId_min: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentDate_min` of type `Date`
  """
  paymentDate_min: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentId_min` of type `Int`
  """
  paymentId_min: OrderDirection
  """
  ✨ Generated from Field `Payment`.`amount_max` of type `Float`
  """
  amount_max: OrderDirection
  """
  ✨ Generated from Field `Payment`.`bookingId_max` of type `Int`
  """
  bookingId_max: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentDate_max` of type `Date`
  """
  paymentDate_max: OrderDirection
  """
  ✨ Generated from Field `Payment`.`paymentId_max` of type `Int`
  """
  paymentId_max: OrderDirection
}
"""
✨ Generated data input type for table 'Room'. It includes all necessary fields for creating or upserting rows into table.
"""
input Room_Data {
  """
  ✨ Generated from Field `Room`.`roomId` of type `Int!`
  """
  roomId: Int
  """
  ✨ `_expr` server value variant of `roomId` (✨ Generated from Field `Room`.`roomId` of type `Int!`)
  """
  roomId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `roomId` (✨ Generated from Field `Room`.`roomId` of type `Int!`)
  """
  roomId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Room`.`hotelId` of type `Int!`
  """
  hotelId: Int
  """
  ✨ `_expr` server value variant of `hotelId` (✨ Generated from Field `Room`.`hotelId` of type `Int!`)
  """
  hotelId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `hotelId` (✨ Generated from Field `Room`.`hotelId` of type `Int!`)
  """
  hotelId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Room`.`roomTypeId` of type `Int!`
  """
  roomTypeId: Int
  """
  ✨ `_expr` server value variant of `roomTypeId` (✨ Generated from Field `Room`.`roomTypeId` of type `Int!`)
  """
  roomTypeId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `roomTypeId` (✨ Generated from Field `Room`.`roomTypeId` of type `Int!`)
  """
  roomTypeId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Room`.`hotel` of type `Hotel!`
  """
  hotel: Hotel_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Room`.`roomType` of type `RoomType!`
  """
  roomType: RoomType_Key @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Room`.`floorNumber` of type `Int!`
  """
  floorNumber: Int
  """
  ✨ `_expr` server value variant of `floorNumber` (✨ Generated from Field `Room`.`floorNumber` of type `Int!`)
  """
  floorNumber_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `floorNumber` (✨ Generated from Field `Room`.`floorNumber` of type `Int!`)
  """
  floorNumber_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Room`.`roomNumber` of type `String!`
  """
  roomNumber: String
  """
  ✨ `_expr` server value variant of `roomNumber` (✨ Generated from Field `Room`.`roomNumber` of type `String!`)
  """
  roomNumber_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `Room`.`roomStatus` of type `String!`
  """
  roomStatus: String
  """
  ✨ `_expr` server value variant of `roomStatus` (✨ Generated from Field `Room`.`roomStatus` of type `String!`)
  """
  roomStatus_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'Room'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Room_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [Room_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: Room_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [Room_Filter!]
  """
  ✨ Generated from Field `Room`.`roomId` of type `Int!`
  """
  roomId: Int_Filter
  """
  ✨ Generated from Field `Room`.`hotelId` of type `Int!`
  """
  hotelId: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomTypeId` of type `Int!`
  """
  roomTypeId: Int_Filter
  """
  ✨ Generated from Field `Room`.`hotel` of type `Hotel!`
  """
  hotel: Hotel_Filter
  """
  ✨ Generated from Field `Room`.`roomType` of type `RoomType!`
  """
  roomType: RoomType_Filter
  """
  ✨ Generated from Field `Room`.`floorNumber` of type `Int!`
  """
  floorNumber: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomNumber` of type `String!`
  """
  roomNumber: String_Filter
  """
  ✨ Generated from Field `Room`.`roomStatus` of type `String!`
  """
  roomStatus: String_Filter
  """
  ✨ Generated from Field `Room`.`bookings_on_room` of type `[Booking!]!`
  """
  bookings_on_room: Booking_ListFilter
}
"""
✨ Generated first-row input type for table 'Room'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input Room_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [Room_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: Room_Filter
}
"""
✨ Generated having input type for table 'Room'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input Room_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [Room_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: Room_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [Room_Having!]
  """
  ✨ Generated from Field `Room`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `Room`.`floorNumber_count` of type `Int!`
  """
  floorNumber_count: Int_Filter
  """
  ✨ Generated from Field `Room`.`hotelId_count` of type `Int!`
  """
  hotelId_count: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomId_count` of type `Int!`
  """
  roomId_count: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomNumber_count` of type `Int!`
  """
  roomNumber_count: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomStatus_count` of type `Int!`
  """
  roomStatus_count: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomTypeId_count` of type `Int!`
  """
  roomTypeId_count: Int_Filter
  """
  ✨ Generated from Field `Room`.`floorNumber_sum` of type `Int`
  """
  floorNumber_sum: Int_Filter
  """
  ✨ Generated from Field `Room`.`hotelId_sum` of type `Int`
  """
  hotelId_sum: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomId_sum` of type `Int`
  """
  roomId_sum: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomTypeId_sum` of type `Int`
  """
  roomTypeId_sum: Int_Filter
  """
  ✨ Generated from Field `Room`.`floorNumber_avg` of type `Float`
  """
  floorNumber_avg: Float_Filter
  """
  ✨ Generated from Field `Room`.`hotelId_avg` of type `Float`
  """
  hotelId_avg: Float_Filter
  """
  ✨ Generated from Field `Room`.`roomId_avg` of type `Float`
  """
  roomId_avg: Float_Filter
  """
  ✨ Generated from Field `Room`.`roomTypeId_avg` of type `Float`
  """
  roomTypeId_avg: Float_Filter
  """
  ✨ Generated from Field `Room`.`floorNumber_min` of type `Int`
  """
  floorNumber_min: Int_Filter
  """
  ✨ Generated from Field `Room`.`hotelId_min` of type `Int`
  """
  hotelId_min: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomId_min` of type `Int`
  """
  roomId_min: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomTypeId_min` of type `Int`
  """
  roomTypeId_min: Int_Filter
  """
  ✨ Generated from Field `Room`.`floorNumber_max` of type `Int`
  """
  floorNumber_max: Int_Filter
  """
  ✨ Generated from Field `Room`.`hotelId_max` of type `Int`
  """
  hotelId_max: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomId_max` of type `Int`
  """
  roomId_max: Int_Filter
  """
  ✨ Generated from Field `Room`.`roomTypeId_max` of type `Int`
  """
  roomTypeId_max: Int_Filter
}
"""
✨ Generated key input type for table 'Room'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input Room_Key {
  """
  ✨ Generated from Field `Room`.`roomId` of type `Int!`
  """
  roomId: Int
  """
  ✨ `_expr` server value variant of `roomId` (✨ Generated from Field `Room`.`roomId` of type `Int!`)
  """
  roomId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'Room'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input Room_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: Room_Filter
}
"""
✨ Generated order input type for table 'Room'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input Room_Order {
  """
  ✨ Generated from Field `Room`.`roomId` of type `Int!`
  """
  roomId: OrderDirection
  """
  ✨ Generated from Field `Room`.`hotelId` of type `Int!`
  """
  hotelId: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomTypeId` of type `Int!`
  """
  roomTypeId: OrderDirection
  """
  ✨ Generated from Field `Room`.`hotel` of type `Hotel!`
  """
  hotel: Hotel_Order
  """
  ✨ Generated from Field `Room`.`roomType` of type `RoomType!`
  """
  roomType: RoomType_Order
  """
  ✨ Generated from Field `Room`.`floorNumber` of type `Int!`
  """
  floorNumber: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomNumber` of type `String!`
  """
  roomNumber: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomStatus` of type `String!`
  """
  roomStatus: OrderDirection
  """
  ✨ Generated from Field `Room`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `Room`.`floorNumber_count` of type `Int!`
  """
  floorNumber_count: OrderDirection
  """
  ✨ Generated from Field `Room`.`hotelId_count` of type `Int!`
  """
  hotelId_count: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomId_count` of type `Int!`
  """
  roomId_count: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomNumber_count` of type `Int!`
  """
  roomNumber_count: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomStatus_count` of type `Int!`
  """
  roomStatus_count: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomTypeId_count` of type `Int!`
  """
  roomTypeId_count: OrderDirection
  """
  ✨ Generated from Field `Room`.`floorNumber_sum` of type `Int`
  """
  floorNumber_sum: OrderDirection
  """
  ✨ Generated from Field `Room`.`hotelId_sum` of type `Int`
  """
  hotelId_sum: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomId_sum` of type `Int`
  """
  roomId_sum: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomTypeId_sum` of type `Int`
  """
  roomTypeId_sum: OrderDirection
  """
  ✨ Generated from Field `Room`.`floorNumber_avg` of type `Float`
  """
  floorNumber_avg: OrderDirection
  """
  ✨ Generated from Field `Room`.`hotelId_avg` of type `Float`
  """
  hotelId_avg: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomId_avg` of type `Float`
  """
  roomId_avg: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomTypeId_avg` of type `Float`
  """
  roomTypeId_avg: OrderDirection
  """
  ✨ Generated from Field `Room`.`floorNumber_min` of type `Int`
  """
  floorNumber_min: OrderDirection
  """
  ✨ Generated from Field `Room`.`hotelId_min` of type `Int`
  """
  hotelId_min: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomId_min` of type `Int`
  """
  roomId_min: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomTypeId_min` of type `Int`
  """
  roomTypeId_min: OrderDirection
  """
  ✨ Generated from Field `Room`.`floorNumber_max` of type `Int`
  """
  floorNumber_max: OrderDirection
  """
  ✨ Generated from Field `Room`.`hotelId_max` of type `Int`
  """
  hotelId_max: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomId_max` of type `Int`
  """
  roomId_max: OrderDirection
  """
  ✨ Generated from Field `Room`.`roomTypeId_max` of type `Int`
  """
  roomTypeId_max: OrderDirection
}
"""
✨ Generated data input type for table 'RoomType'. It includes all necessary fields for creating or upserting rows into table.
"""
input RoomType_Data {
  """
  ✨ Generated from Field `RoomType`.`roomTypeId` of type `Int!`
  """
  roomTypeId: Int
  """
  ✨ `_expr` server value variant of `roomTypeId` (✨ Generated from Field `RoomType`.`roomTypeId` of type `Int!`)
  """
  roomTypeId_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `roomTypeId` (✨ Generated from Field `RoomType`.`roomTypeId` of type `Int!`)
  """
  roomTypeId_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RoomType`.`capacity` of type `Int!`
  """
  capacity: Int
  """
  ✨ `_expr` server value variant of `capacity` (✨ Generated from Field `RoomType`.`capacity` of type `Int!`)
  """
  capacity_expr: Int_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `capacity` (✨ Generated from Field `RoomType`.`capacity` of type `Int!`)
  """
  capacity_update: [Int_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RoomType`.`description` of type `String`
  """
  description: String
  """
  ✨ `_expr` server value variant of `description` (✨ Generated from Field `RoomType`.`description` of type `String`)
  """
  description_expr: String_Expr @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RoomType`.`pricePerNight` of type `Float!`
  """
  pricePerNight: Float
  """
  ✨ `_expr` server value variant of `pricePerNight` (✨ Generated from Field `RoomType`.`pricePerNight` of type `Float!`)
  """
  pricePerNight_expr: Float_Expr @fdc_forbiddenInVariables
  """
  ✨ `_update` server value variant of `pricePerNight` (✨ Generated from Field `RoomType`.`pricePerNight` of type `Float!`)
  """
  pricePerNight_update: [Float_Update!] @fdc_forbiddenInVariables
  """
  ✨ Generated from Field `RoomType`.`typeName` of type `String!`
  """
  typeName: String
  """
  ✨ `_expr` server value variant of `typeName` (✨ Generated from Field `RoomType`.`typeName` of type `String!`)
  """
  typeName_expr: String_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated filter input type for table 'RoomType'. This input allows filtering objects using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RoomType_Filter {
  """
  Apply multiple filter conditions using `AND` logic.
  """
  _and: [RoomType_Filter!]
  """
  Negate the result of the provided filter condition.
  """
  _not: RoomType_Filter
  """
  Apply multiple filter conditions using `OR` logic.
  """
  _or: [RoomType_Filter!]
  """
  ✨ Generated from Field `RoomType`.`roomTypeId` of type `Int!`
  """
  roomTypeId: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`capacity` of type `Int!`
  """
  capacity: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`description` of type `String`
  """
  description: String_Filter
  """
  ✨ Generated from Field `RoomType`.`pricePerNight` of type `Float!`
  """
  pricePerNight: Float_Filter
  """
  ✨ Generated from Field `RoomType`.`typeName` of type `String!`
  """
  typeName: String_Filter
  """
  ✨ Generated from Field `RoomType`.`rooms_on_roomType` of type `[Room!]!`
  """
  rooms_on_roomType: Room_ListFilter
}
"""
✨ Generated first-row input type for table 'RoomType'. This input selects the first row matching the filter criteria, ordered according to the specified conditions.
"""
input RoomType_FirstRow {
  """
  Order the result by the specified fields.
  """
  orderBy: [RoomType_Order!]
  """
  Filters rows based on the specified conditions.
  """
  where: RoomType_Filter
}
"""
✨ Generated having input type for table 'RoomType'. This input allows you to filter groups during aggregate queries using various conditions. Use `_or`, `_and`, and `_not` to compose complex filters.
"""
input RoomType_Having {
  """
  Apply multiple Having conditions using `AND` logic.
  """
  _and: [RoomType_Having!]
  """
  Whether to apply DISTINCT to the aggregate function.
  """
  _distinct: Boolean
  """
  Negate the result of the provided Having condition.
  """
  _not: RoomType_Having
  """
  Apply multiple Having conditions using `OR` logic.
  """
  _or: [RoomType_Having!]
  """
  ✨ Generated from Field `RoomType`.`_count` of type `Int!`
  """
  _count: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`capacity_count` of type `Int!`
  """
  capacity_count: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`description_count` of type `Int!`
  """
  description_count: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_count` of type `Int!`
  """
  pricePerNight_count: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_count` of type `Int!`
  """
  roomTypeId_count: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`typeName_count` of type `Int!`
  """
  typeName_count: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`capacity_sum` of type `Int`
  """
  capacity_sum: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_sum` of type `Float`
  """
  pricePerNight_sum: Float_Filter
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_sum` of type `Int`
  """
  roomTypeId_sum: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`capacity_avg` of type `Float`
  """
  capacity_avg: Float_Filter
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_avg` of type `Float`
  """
  pricePerNight_avg: Float_Filter
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_avg` of type `Float`
  """
  roomTypeId_avg: Float_Filter
  """
  ✨ Generated from Field `RoomType`.`capacity_min` of type `Int`
  """
  capacity_min: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_min` of type `Float`
  """
  pricePerNight_min: Float_Filter
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_min` of type `Int`
  """
  roomTypeId_min: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`capacity_max` of type `Int`
  """
  capacity_max: Int_Filter
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_max` of type `Float`
  """
  pricePerNight_max: Float_Filter
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_max` of type `Int`
  """
  roomTypeId_max: Int_Filter
}
"""
✨ Generated key input type for table 'RoomType'. It represents the primary key fields used to uniquely identify a row in the table.
"""
input RoomType_Key {
  """
  ✨ Generated from Field `RoomType`.`roomTypeId` of type `Int!`
  """
  roomTypeId: Int
  """
  ✨ `_expr` server value variant of `roomTypeId` (✨ Generated from Field `RoomType`.`roomTypeId` of type `Int!`)
  """
  roomTypeId_expr: Int_Expr @fdc_forbiddenInVariables
}
"""
✨ Generated list filter input type for table 'RoomType'. This input applies filtering logic based on the count or existence of related objects that matches certain criteria.
"""
input RoomType_ListFilter {
  """
  The desired number of objects that match the condition (defaults to at least one).
  """
  count: Int_Filter = {gt:0}
  """
  Condition of the related objects to filter for.
  """
  exist: RoomType_Filter
}
"""
✨ Generated order input type for table 'RoomType'. This input defines the sorting order of rows in query results based on one or more fields.
"""
input RoomType_Order {
  """
  ✨ Generated from Field `RoomType`.`roomTypeId` of type `Int!`
  """
  roomTypeId: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`capacity` of type `Int!`
  """
  capacity: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`description` of type `String`
  """
  description: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`pricePerNight` of type `Float!`
  """
  pricePerNight: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`typeName` of type `String!`
  """
  typeName: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`_count` of type `Int!`
  """
  _count: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`capacity_count` of type `Int!`
  """
  capacity_count: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`description_count` of type `Int!`
  """
  description_count: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_count` of type `Int!`
  """
  pricePerNight_count: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_count` of type `Int!`
  """
  roomTypeId_count: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`typeName_count` of type `Int!`
  """
  typeName_count: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`capacity_sum` of type `Int`
  """
  capacity_sum: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_sum` of type `Float`
  """
  pricePerNight_sum: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_sum` of type `Int`
  """
  roomTypeId_sum: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`capacity_avg` of type `Float`
  """
  capacity_avg: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_avg` of type `Float`
  """
  pricePerNight_avg: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_avg` of type `Float`
  """
  roomTypeId_avg: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`capacity_min` of type `Int`
  """
  capacity_min: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_min` of type `Float`
  """
  pricePerNight_min: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_min` of type `Int`
  """
  roomTypeId_min: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`capacity_max` of type `Int`
  """
  capacity_max: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`pricePerNight_max` of type `Float`
  """
  pricePerNight_max: OrderDirection
  """
  ✨ Generated from Field `RoomType`.`roomTypeId_max` of type `Int`
  """
  roomTypeId_max: OrderDirection
}
